version: '3.3'
services:
  web:
    container_name: sn-php-apache
    image: php:8.0-apache
    build: .
    volumes:
      - ./sn/src:/var/www/html/
    ports:
      - 8888:80

  db:
    container_name: sn-mysql
    image: mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --secure-file-priv=/data
      --init-file /data/application/init.sql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./sn/data:/data
      - ./init.sql:/data/application/init.sql

  phpmyadmin:
    container_name: sn-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  sftp:
    container_name: sn-sftp
    image: atmoz/sftp
    volumes:
      - ./sn:/home/admin/upload
    ports:
      - "2222:22"
    command: admin:admin:1001

  grafana:
    container_name: sn-grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    
  grafana_renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081:8081