version: '3.8'
services:
  php-apache-environment:
    container_name: sn-php-apache
    image: php:8.0-apache
    volumes:
      - ./sn/src:/var/www/html/
    ports:
      - 8888:80

  db:
    container_name: sn-mysql
    image: mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --secure-file-priv=/data
      --init-file /data/application/init.sql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./sn/data:/data
      - ./init.sql:/data/application/init.sql

  #adminer:
  #  container_name: sn-adminer
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080

  phpmyadmin:
    container_name: sn-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  sftp:
    container_name: sn-sftp
    image: atmoz/sftp
    volumes:
        - ./sn:/home/admin/upload
    ports:
        - "2222:22"
    command: admin:admin:1001
