{
 "title": "LED",
 "time": { "from": "2022-11-23T10:06:12.000Z", "to": "2022-11-23T10:30:00.000Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "LED1: Red",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "sensornetwork",
     "rawSql": "SELECT \n  $__timeGroup(time, '1s') as time,\n  AVG(value) as \"LED1: Red\"\nFROM LED\nWHERE did=1\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "LED1: Green",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "dataset": "sensornetwork",
     "rawSql": "SELECT \n  $__timeGroup(time, '1s') as time,\n  AVG(value) as \"LED1: Green\"\nFROM LED\nWHERE did=2\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "LED1: Blue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "dataset": "sensornetwork",
     "rawSql": "SELECT \n  $__timeGroup(time, '1s') as time,\n  AVG(value) as \"LED1: Blue\"\nFROM LED\nWHERE did=3\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Number of finger",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensornetwork",
     "rawSql": "SELECT \n  $__timeGroup(time, '1s') as time,\n  value as \"Number of Finger\"\nFROM finger\n"
    }
   ]
  },
  {
   "title": "Number of finger",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "dataset": "sensornetwork",
     "rawSql": "SELECT \n  $__timeGroup(time, '1s') as time,\n  value as \"Number of Finger\"\nFROM finger\n"
    }
   ]
  }
 ]
}