{
 "title": "sensor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensornetwork",
     "rawSql": "SELECT \n  $__timeGroup(time, '1s') as time,\n  led_r as \"LED_Red\", led_g as \"LED_Green\", led_b as \"LED_Blue\"\nFROM sensor"
    }
   ]
  },
  {
   "title": "RGB LED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "dataset": "sensornetwork",
     "rawSql": "SELECT \n  $__timeGroup(time, '1s') as time,\n  led_r as \"LED_Red\", led_g as \"LED_Green\", led_b as \"LED_Blue\"\nFROM sensor"
    }
   ]
  },
  {
   "title": "Number of finger",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensornetwork",
     "rawSql": "SELECT \n  $__timeGroup(time, '1s') as time,\n  finger as \"Number of Finger\"\nFROM sensor\n"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "dataset": "sensornetwork",
     "rawSql": "SELECT \n  $__timeGroup(time, '1s') as time,\n  finger as \"Number of Finger\"\nFROM sensor\n"
    }
   ]
  },
  {
   "title": "Angle of servo (deg)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensornetwork",
     "rawSql": "SELECT \n  $__timeGroup(time, '1s') as time,\n  servo_angle as \"Angle of Servo\"\nFROM sensor\n"
    }
   ]
  },
  {
   "title": "Angle of servo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "dataset": "sensornetwork",
     "rawSql": "SELECT \n  $__timeGroup(time, '1s') as time,\n  servo_angle as \"Angle of Servo\"\nFROM sensor"
    }
   ]
  }
 ]
}